<?php

/**
 * @file
 * Contains dhis.module.
 */
use Drupal\dhis\Entity\OrganisationUnit;
use Drupal\dhis\Entity\DataElement;

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dhis_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dhis module.
    case 'help.page.dhis':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('DHIS2 Module for connecting and retrieving metadata from a DHIS2 Instance') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function dhis_theme($existing, $type, $theme, $path) {
  return [
    'dhis' => [
      'template' => 'dhis',
      'variables' => array('test_var' => NULL),
    ],
  ];
}
/**
 * Implements hook_toolbar_alter().
 */
function dhis_toolbar_alter(&$items) {
    $items['administration']['#attached']['library'][] = 'dhis/toolbar';
}